### ISSUE TITLE
Plot not compatible with Bokeh 0.9.1

### ISSUE THREAD

**Issue by rizar** [mila-udem/blocks-extras#15]
Sad but true, see also the discussion in #11. @mdda , if you feel you can tackle this, that would be great, since I am by no means a Bokeh guru.

**Comment by mdda** [comment]
Ok - I'm game for having a look at this.  My original problem with fixing #11 is that it seems to work (for me) against v0.9.0 from PyPI (and the bokeh changelog doesn't include any obvious smoking gun).  Let me play around with Plot against bokeh:master over the weekend and see where I get...   

For now, my acceptance test will be whether the sample iPython notebook ( https://github.com/mdda/pycon.sg-2015_deep-learning/blob/master/ipynb/1-LivePlotting.ipynb ) works.

**Comment by rizar** [comment]
Bokeh 0.9.0 works for me as well.  But now 0.9.1 is also on PyPI. And indeed the changelog does not give a cue.

**Comment by rodrigob** [comment]
This seems broken (bokeh 0.9.3), any chance of having it fixed ?

**Comment by dwf** [comment]
This is a bug in Bokeh, see bokeh/bokeh#2787. Apparently the index page for the Bokeh server was kind of an afterthought, and nobody noticed when it broke following a change to the jQuery settings about 5 months ago ( bokeh/bokeh@607c920 ). I don't really know JS that well or CoffeeScript at all, but if you do, feel free to give it a shot. (I just bisected it yesterday, so there's a chance one of the Continuum guys will have some insight how to fix it in the coming week.)

**Comment by dwf** [comment]
I've managed to fix it, pending the pull request's acceptance. See bokeh/bokeh#2792.

**Comment by rizar** [comment]
That sounds great!

**Comment by dwf** [comment]
![Good news everyone!](http://www.friendlyfiregamecenter.com/blog/wp-content/uploads/2012/08/good-news-everyone.png)

[The relevant PR](https://github.com/bokeh/bokeh/pull/2792) has been merged. There should be a development build of Bokeh out by the end of the week, or latest, early next week. In the mean time, you can take advantage of it by building from master (although building Bokeh is somewhat involved, it is relatively painless with Conda in your arsenal).

**Comment by dwf** [comment]
You can use the release [here](https://github.com/bokeh/bokeh/releases/tag/0.10.0dev-0ac7349), or install with conda: 
```
conda install bokeh==0.10.0dev.78671086 -c bokeh/channel/dev
```
which contains the fix.
