### ISSUE TITLE
Problems with plotting the results

### ISSUE THREAD

**Issue by mateuszmalinowski** [mila-udem/blocks-extras#20]
I am going through the examples in live plotting tutorial (https://blocks.readthedocs.org/en/latest/plotting.html) with bokeh-0.9.0 (newer versions of bokeh yield an error already reported in #15), but I am not getting any figures in the end. 

I use bokeh-server and localhost:5006
The MainLoop have created a new document in Bokeh Documents called 'Plotting examples'.
It also looks there is some communication between main_loop.run() and the server (see the excerpt below).
However I don't see any plots neither during training nor when it is finished.

I tried this under Safari and Iceweasel.

Excerpt:
INFO:tornado.access:200 POST /bokeh/bb/36e95f94-0c8e-462e-9d0e-8a193e05f510/bulkupsert (127.0.0.1) 19.91ms
INFO:tornado.access:200 POST /bokeh/bb/36e95f94-0c8e-462e-9d0e-8a193e05f510/bulkupsert (127.0.0.1) 28.04ms
INFO:tornado.access:200 POST /bokeh/bb/36e95f94-0c8e-462e-9d0e-8a193e05f510/bulkupsert (127.0.0.1) 40.00ms

**Comment by dmitriy-serdyuk** [comment]
Make sure, that you installed bokeh correctly. 

Sometimes there's some issue with CSS styles in bokeh, I had to remove `.collapse{..}` entity using a debugging console.
