### ISSUE TITLE
Blocks-extras issue: BOKEH_AVAILABLE = False

### ISSUE THREAD

**Issue by nitrofortin** [mila-udem/blocks-extras#41]
From plot.py in blocks_extras/extensions/ at line 11:

_from bokeh.plotting import cursession_ 
but _cursession_ does not seem to be support anymore in bokeh 0.11.0. I tried to omit _cursession_ in import step, but it doesn't work either. Any tricks to bypass this? Thanks.

**Comment by dmitriy-serdyuk** [comment]
Right, see discussion in #35 . I guess, the only way is to use bokeh 0.10.
